name: CI

on: ["push", "pull_request"]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Use Node.js 13.x
                uses: actions/setup-node@v1
                with:
                    node-version: 13.x

            -   name: Install dependencies and build
                run: |
                    npm ci
                    npm run lint:ts
                    npm run build
